# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

addons:
  apt:
    packages:
      - rpm
language: scala
scala:
  - 2.12.6
  - 2.11.12
jdk:
  - openjdk8
  - openjdk9
  - openjdk11
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - rm -f $HOME/.ivy2/.sbt.ivy.lock

env:
  global:
    - SBT="sbt -J-Xms1024m -J-Xmx4096m -J-XX:ReservedCodeCacheSize=512m -J-XX:MaxMetaspaceSize=1024m"

before_script:
  - unset _JAVA_OPTIONS
script:
  - $SBT ++$TRAVIS_SCALA_VERSION coverage compile test:compile it:compile || travis_terminate 1
  - $SBT ++$TRAVIS_SCALA_VERSION coverage test
  - $SBT ++$TRAVIS_SCALA_VERSION coverage it:test
  - $SBT ++$TRAVIS_SCALA_VERSION coverage daffodil-cli/universal:packageBin
  - $SBT ++$TRAVIS_SCALA_VERSION coverage daffodil-cli/universal:packageZipTarball
  - $SBT ++$TRAVIS_SCALA_VERSION coverage daffodil-cli/rpm:packageBin
  - $SBT ++$TRAVIS_SCALA_VERSION coverage daffodil-japi/genjavadoc:doc
  - $SBT ++$TRAVIS_SCALA_VERSION coverage daffodil-sapi/doc
  - $SBT ++$TRAVIS_SCALA_VERSION coverage ratCheck || (cat target/rat.txt; exit 1)
  - $SBT ++$TRAVIS_SCALA_VERSION coverage coverageReport
  - $SBT ++$TRAVIS_SCALA_VERSION coverage coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
